apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-cost-effective
  labels:
    app: nginx-cost-effective
spec:
  replicas: 0
  selector:
    matchLabels:
      app: nginx-cost-effective
  template:
    metadata:
      labels:
        app: nginx-cost-effective
    spec:
      containers:
      - name: nginx
        image: nginxdemos/hello:plain-text
        ports:
        - containerPort: 80